/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import React, { useEffect, useRef } from 'react';

export function SantaMeBit(props) {
  const group = useRef()
  useEffect(() => {
    // Stop all other animations
    Object.keys(actions).forEach((key) => {
      actions[key].stop();
    });

    // Play only the "run" animation
    if (actions.run) {
      actions.run.play();
    }
  }, [actions]);
  const { nodes, materials, animations } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/myProjects/glbModels/SantaMeBit.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-17.82, -59.27, -6.8]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.17, 0.22, 0.32]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-78.95, 229.96, 43.67]} rotation={[0, -0.1, -0.2]} scale={[0.2, 0.19, 0.22]} />
          <group position={[-62.99, 175.83, 10.92]} rotation={[0, 0.11, 0.02]}>
            <group name="Polygon_Reduction_1" position={[-41.9, 18.25, -1.21]} rotation={[0, -0.11, -0.02]}>
              <group position={[64.82, -3.51, 2.24]} rotation={[0, 0, 1.6]} scale={[1, 1.87, 1]}>
                <mesh geometry={nodes.Cylinder_Mat1_0.geometry} material={materials['Mat.1']} />
              </group>
              <group position={[0, -6.13, 0]}>
                <mesh
                  geometry={nodes.Polygon_Reduction_1_Material_0_0_1.geometry}
                  material={nodes.Polygon_Reduction_1_Material_0_0_1.material}
                />
                <mesh
                  geometry={nodes.Polygon_Reduction_1_Material_0_0_2.geometry}
                  material={materials.MeditationSanta_Model_9_u1_v1}
                />
                <mesh
                  geometry={nodes.Polygon_Reduction_1_Material_0_0_3.geometry}
                  material={materials.PaletteMaterial001}
                />
                <mesh geometry={nodes.Polygon_Reduction_1_Material_0_0_4.geometry} material={materials.material_0} />
              </group>
              <mesh
                geometry={nodes.Polygon_Reduction_1_Material_0_0001.geometry}
                material={nodes.Polygon_Reduction_1_Material_0_0001.material}
              />
            </group>
            <group position={[10.15, -1.83, 16.35]} rotation={[-Math.PI / 2, 0, 0]}>
              <primitive object={nodes._rootJoint} />
              <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.AN_NPC_Sarara_SK_2__0.geometry} material={nodes.AN_NPC_Sarara_SK_2__0.material} />
              </group>
              <skinnedMesh
                geometry={nodes.Object_87.geometry}
                material={materials['CH_NPC_Pig_MI_PJH.1']}
                skeleton={nodes.Object_87.skeleton}
              />
              <skinnedMesh
                geometry={nodes.Object_88.geometry}
                material={materials['CH_NPC_Pig_Eyelash_PJH.1']}
                skeleton={nodes.Object_88.skeleton}
              />
              <skinnedMesh
                geometry={nodes.Object_89.geometry}
                material={materials['CH_NPC_Pig_EyeBall_MI_PJH.1']}
                skeleton={nodes.Object_89.skeleton}
              />
            </group>
            <group position={[46.74, -1.83, 21.44]} rotation={[-Math.PI / 2, 0, 0]}>
              <primitive object={nodes._rootJoint_1} />
              <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  geometry={nodes.AN_NPC_Sarara_SK_2_3__0.geometry}
                  material={nodes.AN_NPC_Sarara_SK_2_3__0.material}
                />
              </group>
              <skinnedMesh
                geometry={nodes.Object_229.geometry}
                material={materials['CH_NPC_Pig_MI_PJH.3']}
                skeleton={nodes.Object_229.skeleton}
              />
              <skinnedMesh
                geometry={nodes.Object_230.geometry}
                material={materials['CH_NPC_Pig_Eyelash_PJH.3']}
                skeleton={nodes.Object_230.skeleton}
              />
              <skinnedMesh
                geometry={nodes.Object_231.geometry}
                material={materials['CH_NPC_Pig_EyeBall_MI_PJH.3']}
                skeleton={nodes.Object_231.skeleton}
              />
            </group>
            <group position={[13.63, -1.83, -4.07]} rotation={[-Math.PI / 2, 0, 0]}>
              <primitive object={nodes._rootJoint_2} />
              <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.AN_NPC_Sarara_SK__0.geometry} material={nodes.AN_NPC_Sarara_SK__0.material} />
              </group>
              <skinnedMesh
                geometry={nodes.Object_16.geometry}
                material={materials.CH_NPC_Pig_MI_PJH}
                skeleton={nodes.Object_16.skeleton}
              />
              <skinnedMesh
                geometry={nodes.Object_17.geometry}
                material={materials.CH_NPC_Pig_Eyelash_PJH}
                skeleton={nodes.Object_17.skeleton}
              />
              <skinnedMesh
                geometry={nodes.Object_18.geometry}
                material={materials.CH_NPC_Pig_EyeBall_MI_PJH}
                skeleton={nodes.Object_18.skeleton}
              />
            </group>
            <group position={[50.22, -1.83, 1.02]} rotation={[-Math.PI / 2, 0, 0]}>
              <primitive object={nodes._rootJoint_3} />
              <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  geometry={nodes.AN_NPC_Sarara_SK_2_2__0.geometry}
                  material={nodes.AN_NPC_Sarara_SK_2_2__0.material}
                />
              </group>
              <skinnedMesh
                geometry={nodes.Object_158.geometry}
                material={materials['CH_NPC_Pig_MI_PJH.2']}
                skeleton={nodes.Object_158.skeleton}
              />
              <skinnedMesh
                geometry={nodes.Object_159.geometry}
                material={materials['CH_NPC_Pig_Eyelash_PJH.2']}
                skeleton={nodes.Object_159.skeleton}
              />
              <skinnedMesh
                geometry={nodes.Object_160.geometry}
                material={materials['CH_NPC_Pig_EyeBall_MI_PJH.2']}
                skeleton={nodes.Object_160.skeleton}
              />
            </group>
          </group>
        </group>
      </group>
      <group position={[-34.84, 3.28, -3.05]} rotation={[-3.14, 0.72, -0.01]} scale={[37.04, 30.12, 24.27]} />
      <group position={[-38.23, 23.41, -3.1]} rotation={[-Math.PI / 2, -0.17, 0]} scale={[3.11, 2.11, 3.01]}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-38.78, 16.69, 2.67]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.75, 0.71, 0.93]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.03, 0.03, 0.03]}>
          <group position={[0, 9.73, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[38.26, 38.26, 38.26]}>
            <group scale={[2.41, 2.41, 2.01]}>
              <mesh geometry={nodes.model_default002_0001_1.geometry} material={materials['default.001']} />
              <mesh geometry={nodes.model_default002_0001_2.geometry} material={materials['01_-_Default.001']} />
            </group>
          </group>
        </group>
      </group>
      <group position={[-38.56, 17.07, 2.6]} rotation={[-Math.PI / 2, 0, 1.57]} scale={[0.43, 0.36, 0.34]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_39.geometry} material={nodes.Object_39.material} />
          <mesh geometry={nodes.Object_37.geometry} material={nodes.Object_37.material} />
          <group position={[0, 4.83, -0.02]} scale={[0.86, 0.86, 0.86]}>
            <mesh geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} />
          </group>
          <mesh geometry={nodes.Object_13001.geometry} material={nodes.Object_13001.material} />
          <group position={[-1.63, 3.71, -0.27]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={[0.16, 0.16, 0.16]}>
            <mesh geometry={nodes.Object_17001.geometry} material={nodes.Object_17001.material} />
          </group>
          <group position={[1.39, 4.41, -0.27]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={[0.16, 0.16, 0.16]}>
            <mesh geometry={nodes.Object_19.geometry} material={nodes.Object_19.material} />
          </group>
          <group position={[-1.83, 1.67, -0.27]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={[0.12, 0.12, 0.12]}>
            <mesh geometry={nodes.Object_21.geometry} material={nodes.Object_21.material} />
          </group>
          <group position={[-0.74, 4.68, -0.27]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={[0.13, 0.13, 0.13]}>
            <mesh geometry={nodes.Object_23.geometry} material={nodes.Object_23.material} />
          </group>
          <group position={[3.06, 2.91, -0.27]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={[0.11, 0.11, 0.11]}>
            <mesh geometry={nodes.Object_25.geometry} material={nodes.Object_25.material} />
          </group>
          <group position={[-2.21, 0.89, -0.27]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={[0.15, 0.15, 0.15]}>
            <mesh geometry={nodes.Object_27.geometry} material={nodes.Object_27.material} />
          </group>
          <group position={[-1.96, 3.02, -0.27]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={[0.16, 0.16, 0.16]}>
            <mesh geometry={nodes.Object_29.geometry} material={nodes.Object_29.material} />
          </group>
          <group position={[2.52, 1.12, -0.27]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={[0.12, 0.12, 0.12]}>
            <mesh geometry={nodes.Object_31.geometry} material={nodes.Object_31.material} />
          </group>
          <group position={[1.78, 3.35, -0.27]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={[0.13, 0.13, 0.13]}>
            <mesh geometry={nodes.Object_33.geometry} material={nodes.Object_33.material} />
          </group>
          <group position={[1.65, 1.95, -0.27]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={[0.15, 0.15, 0.15]}>
            <mesh geometry={nodes.Object_15001.geometry} material={nodes.Object_15001.material} />
          </group>
          <mesh geometry={nodes.Object_5001.geometry} material={nodes.Object_5001.material} />
          <mesh geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
          <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
          <mesh geometry={nodes.Object_35.geometry} material={nodes.Object_35.material} />
        </group>
      </group>
      <group position={[-38.12, 17.73, -11.68]} rotation={[-Math.PI / 2, -0.11, 1.6]} scale={[0.56, 1.17, 0.68]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.21, -0.57, 0]} rotation={[0, Math.PI / 4, 0]}>
            <mesh geometry={nodes.Object_52.geometry} material={nodes.Object_52.material} />
          </group>
          <group position={[-1.51, -0.56, 0]}>
            <mesh geometry={nodes.Object_54.geometry} material={nodes.Object_54.material} />
          </group>
          <group position={[-0.74, -0.57, -0.28]} rotation={[0, Math.PI / 4, 0]}>
            <mesh geometry={nodes.Object_56.geometry} material={nodes.Object_56.material} />
          </group>
          <group position={[0.29, -0.57, 0.14]}>
            <mesh geometry={nodes.Object_50.geometry} material={nodes.Object_50.material} />
          </group>
          <group position={[-0.52, 3.02, -0.11]} rotation={[0, -0.13, 0]}>
            <mesh geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
          </group>
          <group position={[0.68, 2.83, 0.22]} rotation={[0, 0.13, 0]}>
            <mesh geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
          </group>
          <group position={[1.05, 2.18, -0.06]} rotation={[0, -0.13, 0]}>
            <mesh geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
          </group>
          <group position={[0.79, 1.75, 0.27]} rotation={[0, 0.13, 0]}>
            <mesh geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
          </group>
          <group position={[-0.68, 2.37, 0.28]} rotation={[0, 0.13, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
          </group>
          <group position={[1.24, 1.37, 0.05]} rotation={[0, -0.13, 0]}>
            <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
          </group>
          <group position={[1.63, 1.06, -0.22]} rotation={[0, 0.13, 0]}>
            <mesh geometry={nodes.Object_16001.geometry} material={nodes.Object_16001.material} />
          </group>
          <group position={[1.66, 0.29, -0.16]} rotation={[0, -0.13, 0]}>
            <mesh geometry={nodes.Object_18001.geometry} material={nodes.Object_18001.material} />
          </group>
          <group position={[1.44, -0.14, 0.24]} rotation={[0, 0.06, 0]}>
            <mesh geometry={nodes.Object_20.geometry} material={nodes.Object_20.material} />
          </group>
          <group position={[0.89, -0.25, -0.31]} rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_22.geometry} material={nodes.Object_22.material} />
          </group>
          <group position={[-1.2, -0.06, 0.48]} rotation={[0, -0.13, 0]}>
            <mesh geometry={nodes.Object_24.geometry} material={nodes.Object_24.material} />
          </group>
          <group position={[-1.67, -0.07, 0.05]} rotation={[0, 0.13, 0]}>
            <mesh geometry={nodes.Object_26.geometry} material={nodes.Object_26.material} />
          </group>
          <group position={[-1.76, 0.72, -0.24]} rotation={[0, -0.13, 0]}>
            <mesh geometry={nodes.Object_28.geometry} material={nodes.Object_28.material} />
          </group>
          <group position={[-1.19, 1.4, 0.64]} rotation={[0, 0.13, 0]}>
            <mesh geometry={nodes.Object_30.geometry} material={nodes.Object_30.material} />
          </group>
          <group position={[-1.36, 2.01, -0.18]} rotation={[0, -0.13, 0]}>
            <mesh geometry={nodes.Object_32.geometry} material={nodes.Object_32.material} />
          </group>
          <group position={[0.28, 2.61, 0]}>
            <mesh geometry={nodes.Object_42.geometry} material={nodes.Object_42.material} />
          </group>
          <group position={[0.19, 2.96, 0]}>
            <mesh geometry={nodes.Object_44.geometry} material={nodes.Object_44.material} />
          </group>
          <group position={[-0.19, 2.96, 0]}>
            <mesh geometry={nodes.Object_46.geometry} material={nodes.Object_46.material} />
          </group>
          <group name="star004_22" position={[-0.28, 2.61, 0]}>
            <mesh geometry={nodes.Object_48.geometry} material={nodes.Object_48.material} />
          </group>
          <mesh geometry={nodes.Object_36.geometry} material={nodes.Object_36.material} />
          <group position={[0, 2.73, 0]}>
            <mesh geometry={nodes.Object_38.geometry} material={nodes.Object_38.material} />
          </group>
          <group position={[-0.04, 0.06, -0.01]}>
            <mesh geometry={nodes.Object_40.geometry} material={nodes.Object_40.material} />
          </group>
          <mesh geometry={nodes.Object_34.geometry} material={nodes.Object_34.material} />
        </group>
      </group>
      <group position={[-38.16, 16.54, -11.67]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.03, 0.03, 0.03]}>
          <group position={[0, 9.73, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={38.26}>
            <group scale={[2.41, 2.49, 2.74]}>
              <mesh geometry={nodes.model_default002_0_1.geometry} material={materials['default.002']} />
              <mesh geometry={nodes.model_default002_0_2.geometry} material={materials['01_-_Default']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://racho-devs.s3.us-east-2.amazonaws.com/myProjects/glbModels/SantaMeBit.glb')
