/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 AboutMe.glb for 3D models 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export default function AboutMe(props) {
  const { nodes, materials } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/about/glbDivs/AboutMe.glb')
  return (
    <group position={[-0.5, -0.5, 1.5]}  rotation = {[Math.PI / 2, 0, 0]}  scale={1.85}  {...props} dispose={null}>
      <mesh geometry={nodes.Curve10080.geometry} material={materials.PaletteMaterial001} />
      <instancedMesh args={[nodes.Curve201.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Curve201.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('https://racho-devs.s3.us-east-2.amazonaws.com/about/glbDivs/AboutMe.glb')
