/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export default function CarBit(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/about/glbDivs/CarBit.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.01, -0.2, 0.24]} rotation={[-Math.PI / 2, 0, 0]} scale={[12.31, 12.31, 11.45]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOfaraz1_forMayaAOrear_lights_0.geometry}
              material={materials.forMayaAOrear_lights}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh geometry={nodes.forMayaAOnomer_forMayaAOnumber_0.geometry} material={materials.forMayaAOnumber} />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpCube1_forMayaAOlambert15_0.geometry}
              material={nodes.forMayaAOpCube1_forMayaAOlambert15_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpCube11_forMayaAOlambert15_0.geometry}
              material={nodes.forMayaAOpCube11_forMayaAOlambert15_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpCube12_forMayaAOlambert15_0.geometry}
              material={nodes.forMayaAOpCube12_forMayaAOlambert15_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpCube13_forMayaAOlambert15_0.geometry}
              material={nodes.forMayaAOpCube13_forMayaAOlambert15_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpCube15_forMayaAOlambert15_0.geometry}
              material={nodes.forMayaAOpCube15_forMayaAOlambert15_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpCube4_forMayaAOlambert16_0.geometry}
              material={nodes.forMayaAOpCube4_forMayaAOlambert16_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpCube5_forMayaAOlambert16_0.geometry}
              material={nodes.forMayaAOpCube5_forMayaAOlambert16_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpCube6_forMayaAOlambert15_0.geometry}
              material={nodes.forMayaAOpCube6_forMayaAOlambert15_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpCylinder1_forMayaAOlambert13_0.geometry}
              material={nodes.forMayaAOpCylinder1_forMayaAOlambert13_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpCylinder10_Chrome_0.geometry}
              material={nodes.forMayaAOpCylinder10_Chrome_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpCylinder11_forMayaAOblinn6_0.geometry}
              material={nodes.forMayaAOpCylinder11_forMayaAOblinn6_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpCylinder12_forMayaAOlambert15_0.geometry}
              material={nodes.forMayaAOpCylinder12_forMayaAOlambert15_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpCylinder8_forMayaAOlambert13_0.geometry}
              material={nodes.forMayaAOpCylinder8_forMayaAOlambert13_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface148_forMayaAOblinn11_0_1.geometry}
              material={nodes.forMayaAOpolySurface148_forMayaAOblinn11_0_1.material}
            />
            <mesh
              geometry={nodes.forMayaAOpolySurface148_forMayaAOblinn11_0_2.geometry}
              material={nodes.forMayaAOpolySurface148_forMayaAOblinn11_0_2.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface166_forMayaAOmi_car_paint_phen2_0_1.geometry}
              material={nodes.forMayaAOpolySurface166_forMayaAOmi_car_paint_phen2_0_1.material}
            />
            <mesh
              geometry={nodes.forMayaAOpolySurface166_forMayaAOmi_car_paint_phen2_0_2.geometry}
              material={nodes.forMayaAOpolySurface166_forMayaAOmi_car_paint_phen2_0_2.material}
            />
            <mesh
              geometry={nodes.forMayaAOpolySurface166_forMayaAOmi_car_paint_phen2_0_3.geometry}
              material={nodes.forMayaAOpolySurface166_forMayaAOmi_car_paint_phen2_0_3.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface191_forMayaAOmi_car_paint_phen2_0.geometry}
              material={nodes.forMayaAOpolySurface191_forMayaAOmi_car_paint_phen2_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface200_Chrome_0.geometry}
              material={nodes.forMayaAOpolySurface200_Chrome_0.material}
            />
            <mesh
              geometry={nodes.forMayaAOpolySurface200_forMayaAOGrill2_0.geometry}
              material={materials.forMayaAOGrill2}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface221_Chrome_0.geometry}
              material={nodes.forMayaAOpolySurface221_Chrome_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface266_forMayaAOblinn9_0.geometry}
              material={nodes.forMayaAOpolySurface266_forMayaAOblinn9_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface29_forMayaAOblinn6_0.geometry}
              material={nodes.forMayaAOpolySurface29_forMayaAOblinn6_0.material}
            />
            <mesh
              geometry={nodes.forMayaAOpolySurface29_forMayaAOblinn7_0.geometry}
              material={nodes.forMayaAOpolySurface29_forMayaAOblinn7_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface292_Chrome_0.geometry}
              material={nodes.forMayaAOpolySurface292_Chrome_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface295_Chrome_0.geometry}
              material={nodes.forMayaAOpolySurface295_Chrome_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface297_forMayaAOmi_car_paint_phen2_0.geometry}
              material={nodes.forMayaAOpolySurface297_forMayaAOmi_car_paint_phen2_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface309_forMayaAOblinn6_0.geometry}
              material={nodes.forMayaAOpolySurface309_forMayaAOblinn6_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface310_forMayaAOlambert15_0.geometry}
              material={nodes.forMayaAOpolySurface310_forMayaAOlambert15_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface316_Chrome_0.geometry}
              material={nodes.forMayaAOpolySurface316_Chrome_0.material}
            />
            <mesh
              geometry={nodes.forMayaAOpolySurface316_forMayaAOphong5_0.geometry}
              material={nodes.forMayaAOpolySurface316_forMayaAOphong5_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface322_forMayaAOlambert16_0.geometry}
              material={nodes.forMayaAOpolySurface322_forMayaAOlambert16_0.material}
            />
            <mesh
              geometry={nodes.forMayaAOpolySurface322_forMayaAOlambert17_0.geometry}
              material={nodes.forMayaAOpolySurface322_forMayaAOlambert17_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface324_Chrome_0.geometry}
              material={nodes.forMayaAOpolySurface324_Chrome_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.polySurface320_forMayaAOlambert16_0.geometry}
              material={materials.PaletteMaterial007}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface326_forMayaAOlambert16_0.geometry}
              material={nodes.forMayaAOpolySurface326_forMayaAOlambert16_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface327_Chrome_0.geometry}
              material={nodes.forMayaAOpolySurface327_Chrome_0.material}
            />
            <mesh
              geometry={nodes.forMayaAOpolySurface327_forMayaAOlambert17_0.geometry}
              material={nodes.forMayaAOpolySurface327_forMayaAOlambert17_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpolySurface83_Chrome_2_0_1.geometry}
              material={nodes.forMayaAOpolySurface83_Chrome_2_0_1.material}
            />
            <mesh
              geometry={nodes.forMayaAOpolySurface83_Chrome_2_0_2.geometry}
              material={nodes.forMayaAOpolySurface83_Chrome_2_0_2.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpPipe5_Chrome_0.geometry}
              material={nodes.forMayaAOpPipe5_Chrome_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpSphere2_forMayaAOfrontLights_0.geometry}
              material={nodes.forMayaAOpSphere2_forMayaAOfrontLights_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpSphere3_forMayaAOblinn10_0.geometry}
              material={materials.forMayaAOblinn10}
            />
            <mesh
              geometry={nodes.forMayaAOpSphere3_forMayaAOblinn6_0.geometry}
              material={nodes.forMayaAOpSphere3_forMayaAOblinn6_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpSphere7_Chrome_0.geometry}
              material={nodes.forMayaAOpSphere7_Chrome_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOpTorus1_Chrome_0.geometry}
              material={nodes.forMayaAOpTorus1_Chrome_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.forMayaAOReshotka_Chrome_0.geometry}
              material={nodes.forMayaAOReshotka_Chrome_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh geometry={nodes.forMayaAOtruba_Chrome_0.geometry} material={nodes.forMayaAOtruba_Chrome_0.material} />
            <mesh
              geometry={nodes.forMayaAOtruba_forMayaAOlambert15_0.geometry}
              material={nodes.forMayaAOtruba_forMayaAOlambert15_0.material}
            />
            <mesh
              geometry={nodes.forMayaAOtruba_forMayaAOmi_car_paint_phen2_0.geometry}
              material={nodes.forMayaAOtruba_forMayaAOmi_car_paint_phen2_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh geometry={nodes.forMayaAOznachok_forMayaAOAlpha_0.geometry} material={materials.forMayaAOAlpha} />
          </group>
          <group position={[-0.04, 0.09, 0.12]} rotation={[Math.PI / 2, 0, 0]} scale={[0, 0, 0]}>
            <group position={[-1, 0.67, 11]} scale={[1.01, 0.9, 0.9]}>
              <mesh geometry={nodes.pCube1_lamp1_0.geometry} material={nodes.pCube1_lamp1_0.material} />
            </group>
            <group position={[27.08, 0.67, 11]} scale={[1.01, 0.9, 0.9]}>
              <mesh geometry={nodes.pCube2_lamp1_0.geometry} material={nodes.pCube2_lamp1_0.material} />
            </group>
            <group position={[-1, 0, 11]} scale={[0.67, 1, 0.67]}>
              <mesh geometry={nodes.pTorus1_Chrome_2_0.geometry} material={nodes.pTorus1_Chrome_2_0.material} />
            </group>
            <group position={[27.08, 0, 11]} scale={[0.67, 1, 0.67]}>
              <mesh geometry={nodes.pTorus2_Chrome_2_0.geometry} material={nodes.pTorus2_Chrome_2_0.material} />
            </group>
          </group>
          <group position={[-0.31, 0.12, -0.03]} rotation={[Math.PI / 2, -0.2, 0.27]} scale={[0.01, 0.01, 0.01]}>
            <group position={[0.33, 5.83, -0.37]} rotation={[0.09, -0.02, -0.15]}>
              <group position={[0.14, 0, 1.9]} rotation={[0, 0.05, 0]}>
                <group position={[40.84, 0.53, -1.95]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.41, 0.5, 0.41]}>
                  <mesh
                    geometry={nodes.pCylinder2_chromedvorn_0.geometry}
                    material={nodes.pCylinder2_chromedvorn_0.material}
                  />
                </group>
              </group>
            </group>
            <group position={[30.67, 0.51, -0.62]} rotation={[0.46, 0.25, 0]} scale={[0.16, 0.16, 0.16]}>
              <mesh geometry={nodes.polySurface354_rezinDvorn_0.geometry} material={materials.rezinDvorn} />
              <mesh
                geometry={nodes.polySurface355_chromedvorn_0.geometry}
                material={nodes.polySurface355_chromedvorn_0.material}
              />
            </group>
          </group>
          <group position={[-0.03, 0.08, -0.03]} rotation={[-0.08, -0.27, -0.02]} scale={[0, 0, 0]} />
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh geometry={nodes.polySurface319_Chrome_0.geometry} material={nodes.polySurface319_Chrome_0.material} />
            <mesh
              geometry={nodes.polySurface319_forMayaAOphong5_0.geometry}
              material={nodes.polySurface319_forMayaAOphong5_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.polySurface322_forMayaAOblinn6_0.geometry}
              material={nodes.polySurface322_forMayaAOblinn6_0.material}
            />
            <mesh
              geometry={nodes.polySurface322_forMayaAOblinn9_0.geometry}
              material={nodes.polySurface322_forMayaAOblinn9_0.material}
            />
          </group>
          <group position={[0, 0.05, -0.05]} rotation={[-0.26, 0, 0]} scale={[0.01, 0.01, 0.01]}>
            <mesh
              geometry={nodes.polySurface347_Chrome_2_0.geometry}
              material={nodes.polySurface347_Chrome_2_0.material}
            />
            <mesh geometry={nodes.polySurface347_logo222_0.geometry} material={materials.logo222} />
          </group>
          <group scale={[0.01, 0.01, 0.01]}>
            <mesh geometry={nodes.polySurface5_Chrome_0.geometry} material={nodes.polySurface5_Chrome_0.material} />
            <mesh
              geometry={nodes.polySurface5_forMayaAOblinn6_0.geometry}
              material={nodes.polySurface5_forMayaAOblinn6_0.material}
            />
            <mesh
              geometry={nodes.polySurface5_forMayaAOblinn7_0.geometry}
              material={nodes.polySurface5_forMayaAOblinn7_0.material}
            />
            <mesh
              geometry={nodes.polySurface5_forMayaAOblinn9_0.geometry}
              material={nodes.polySurface5_forMayaAOblinn9_0.material}
            />
            <mesh
              geometry={nodes.polySurface5_forMayaAOlambert16_0.geometry}
              material={nodes.polySurface5_forMayaAOlambert16_0.material}
            />
          </group>
          <group scale={[0.01, 0.01, 0.01]} />
        </group>
      </group>
      <group position={[0, 0, -2.83]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[0, 0.37, 0]}>
            <mesh
              geometry={nodes.Pelota_Pixar_Mat_0.geometry}
              material={materials.material}
              position={[-142.7, 22.28, 140]}
              rotation={[0, -0.35, 0]}
              scale={[0.36, 0.37, 0.38]}
            />
          </group>
        </group>
      </group>
      <group position={[0, -0.05, -0.43]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
      <group position={[1.6, -0.05, -0.43]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
      <group position={[1.6, 0, -2.83]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[0, 0.37, 0]}>
            <mesh
              geometry={nodes.Pelota_Pixar_Mat_0003.geometry}
              material={materials['material.003']}
              position={[-138.55, 22.28, 141.61]}
              rotation={[0, -0.35, 0]}
              scale={[0.36, 0.37, 0.38]}
            />
          </group>
        </group>
      </group>
      <group position={[1.6, 0, -0.46]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.97, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <group rotation={[0, 0.37, 0]}>
            <mesh
              geometry={nodes.Pelota_Pixar_Mat_0001.geometry}
              material={materials['material.004']}
              position={[-140.97, 22.28, 147.84]}
              rotation={[0, -0.35, 0]}
              scale={[0.36, 0.37, 0.39]}
            />
          </group>
        </group>
      </group>
      <group position={[0, 0, -0.46]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.97, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <group rotation={[0, 0.37, 0]}>
            <mesh
              geometry={nodes.Pelota_Pixar_Mat_0002.geometry}
              material={materials['material.005']}
              position={[-145.12, 22.28, 146.23]}
              rotation={[0, -0.35, 0]}
              scale={[0.36, 0.37, 0.39]}
            />
          </group>
        </group>
      </group>
      <mesh
        geometry={nodes.UfoPurpleBod1014.geometry}
        material={nodes.UfoPurpleBod1014.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1015.geometry}
        material={nodes.UfoPurpleBod1015.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1019.geometry}
        material={nodes.UfoPurpleBod1019.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1026.geometry}
        material={nodes.UfoPurpleBod1026.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1027.geometry}
        material={nodes.UfoPurpleBod1027.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1031.geometry}
        material={nodes.UfoPurpleBod1031.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1032.geometry}
        material={nodes.UfoPurpleBod1032.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1033.geometry}
        material={nodes.UfoPurpleBod1033.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1047.geometry}
        material={nodes.UfoPurpleBod1047.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1049.geometry}
        material={nodes.UfoPurpleBod1049.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1050.geometry}
        material={nodes.UfoPurpleBod1050.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1053.geometry}
        material={nodes.UfoPurpleBod1053.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1054.geometry}
        material={nodes.UfoPurpleBod1054.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1060.geometry}
        material={nodes.UfoPurpleBod1060.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1061.geometry}
        material={nodes.UfoPurpleBod1061.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1062.geometry}
        material={nodes.UfoPurpleBod1062.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1063.geometry}
        material={nodes.UfoPurpleBod1063.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1064.geometry}
        material={nodes.UfoPurpleBod1064.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1065.geometry}
        material={nodes.UfoPurpleBod1065.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1066.geometry}
        material={nodes.UfoPurpleBod1066.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1067.geometry}
        material={nodes.UfoPurpleBod1067.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1068.geometry}
        material={nodes.UfoPurpleBod1068.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1069.geometry}
        material={nodes.UfoPurpleBod1069.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1070.geometry}
        material={nodes.UfoPurpleBod1070.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1071.geometry}
        material={nodes.UfoPurpleBod1071.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1072.geometry}
        material={nodes.UfoPurpleBod1072.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1073.geometry}
        material={nodes.UfoPurpleBod1073.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1074.geometry}
        material={nodes.UfoPurpleBod1074.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1075.geometry}
        material={nodes.UfoPurpleBod1075.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1076.geometry}
        material={nodes.UfoPurpleBod1076.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1077.geometry}
        material={nodes.UfoPurpleBod1077.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1078.geometry}
        material={nodes.UfoPurpleBod1078.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1079.geometry}
        material={nodes.UfoPurpleBod1079.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1080.geometry}
        material={nodes.UfoPurpleBod1080.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1081.geometry}
        material={nodes.UfoPurpleBod1081.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1082.geometry}
        material={nodes.UfoPurpleBod1082.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1083.geometry}
        material={nodes.UfoPurpleBod1083.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1084.geometry}
        material={nodes.UfoPurpleBod1084.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1085.geometry}
        material={nodes.UfoPurpleBod1085.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1086.geometry}
        material={nodes.UfoPurpleBod1086.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1087.geometry}
        material={nodes.UfoPurpleBod1087.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1088.geometry}
        material={nodes.UfoPurpleBod1088.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1089.geometry}
        material={nodes.UfoPurpleBod1089.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1090.geometry}
        material={nodes.UfoPurpleBod1090.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1091.geometry}
        material={nodes.UfoPurpleBod1091.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1092.geometry}
        material={nodes.UfoPurpleBod1092.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1093.geometry}
        material={nodes.UfoPurpleBod1093.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1094.geometry}
        material={nodes.UfoPurpleBod1094.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1095.geometry}
        material={nodes.UfoPurpleBod1095.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1112.geometry}
        material={nodes.UfoPurpleBod1112.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1113.geometry}
        material={nodes.UfoPurpleBod1113.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1115.geometry}
        material={nodes.UfoPurpleBod1115.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1120.geometry}
        material={nodes.UfoPurpleBod1120.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1121.geometry}
        material={nodes.UfoPurpleBod1121.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1124.geometry}
        material={nodes.UfoPurpleBod1124.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1125.geometry}
        material={nodes.UfoPurpleBod1125.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1127.geometry}
        material={nodes.UfoPurpleBod1127.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1132.geometry}
        material={nodes.UfoPurpleBod1132.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1133.geometry}
        material={nodes.UfoPurpleBod1133.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1138.geometry}
        material={nodes.UfoPurpleBod1138.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1139.geometry}
        material={nodes.UfoPurpleBod1139.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1143.geometry}
        material={nodes.UfoPurpleBod1143.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1147.geometry}
        material={nodes.UfoPurpleBod1147.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1148.geometry}
        material={nodes.UfoPurpleBod1148.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1149.geometry}
        material={nodes.UfoPurpleBod1149.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1150.geometry}
        material={nodes.UfoPurpleBod1150.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1151.geometry}
        material={nodes.UfoPurpleBod1151.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1152.geometry}
        material={nodes.UfoPurpleBod1152.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1156.geometry}
        material={nodes.UfoPurpleBod1156.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1158.geometry}
        material={nodes.UfoPurpleBod1158.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1159.geometry}
        material={nodes.UfoPurpleBod1159.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1160.geometry}
        material={nodes.UfoPurpleBod1160.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1161.geometry}
        material={nodes.UfoPurpleBod1161.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1162.geometry}
        material={nodes.UfoPurpleBod1162.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1167.geometry}
        material={nodes.UfoPurpleBod1167.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1168.geometry}
        material={nodes.UfoPurpleBod1168.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1169.geometry}
        material={nodes.UfoPurpleBod1169.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1170.geometry}
        material={nodes.UfoPurpleBod1170.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1171.geometry}
        material={nodes.UfoPurpleBod1171.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1172.geometry}
        material={nodes.UfoPurpleBod1172.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1174.geometry}
        material={nodes.UfoPurpleBod1174.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1175.geometry}
        material={nodes.UfoPurpleBod1175.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1214.geometry}
        material={nodes.UfoPurpleBod1214.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1216.geometry}
        material={nodes.UfoPurpleBod1216.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1222.geometry}
        material={nodes.UfoPurpleBod1222.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1229.geometry}
        material={nodes.UfoPurpleBod1229.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1234.geometry}
        material={nodes.UfoPurpleBod1234.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1239.geometry}
        material={nodes.UfoPurpleBod1239.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1245.geometry}
        material={nodes.UfoPurpleBod1245.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1255.geometry}
        material={nodes.UfoPurpleBod1255.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1270.geometry}
        material={nodes.UfoPurpleBod1270.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1278.geometry}
        material={nodes.UfoPurpleBod1278.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1282.geometry}
        material={nodes.UfoPurpleBod1282.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1286.geometry}
        material={nodes.UfoPurpleBod1286.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1290.geometry}
        material={nodes.UfoPurpleBod1290.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1302.geometry}
        material={nodes.UfoPurpleBod1302.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1306.geometry}
        material={nodes.UfoPurpleBod1306.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1308.geometry}
        material={nodes.UfoPurpleBod1308.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1314.geometry}
        material={nodes.UfoPurpleBod1314.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1321.geometry}
        material={nodes.UfoPurpleBod1321.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1326.geometry}
        material={nodes.UfoPurpleBod1326.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1331.geometry}
        material={nodes.UfoPurpleBod1331.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1345.geometry}
        material={nodes.UfoPurpleBod1345.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1349.geometry}
        material={nodes.UfoPurpleBod1349.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1354.geometry}
        material={nodes.UfoPurpleBod1354.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1358.geometry}
        material={nodes.UfoPurpleBod1358.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1362.geometry}
        material={nodes.UfoPurpleBod1362.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1366.geometry}
        material={nodes.UfoPurpleBod1366.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1368.geometry}
        material={nodes.UfoPurpleBod1368.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1372.geometry}
        material={nodes.UfoPurpleBod1372.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1376.geometry}
        material={nodes.UfoPurpleBod1376.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1382.geometry}
        material={nodes.UfoPurpleBod1382.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1388.geometry}
        material={nodes.UfoPurpleBod1388.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1392.geometry}
        material={nodes.UfoPurpleBod1392.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1394.geometry}
        material={nodes.UfoPurpleBod1394.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1395.geometry}
        material={nodes.UfoPurpleBod1395.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1401.geometry}
        material={nodes.UfoPurpleBod1401.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1403.geometry}
        material={nodes.UfoPurpleBod1403.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1410.geometry}
        material={nodes.UfoPurpleBod1410.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1411.geometry}
        material={nodes.UfoPurpleBod1411.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1417.geometry}
        material={nodes.UfoPurpleBod1417.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1418.geometry}
        material={nodes.UfoPurpleBod1418.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1422.geometry}
        material={nodes.UfoPurpleBod1422.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1423.geometry}
        material={nodes.UfoPurpleBod1423.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1424.geometry}
        material={nodes.UfoPurpleBod1424.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1426.geometry}
        material={nodes.UfoPurpleBod1426.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1428.geometry}
        material={nodes.UfoPurpleBod1428.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1433.geometry}
        material={nodes.UfoPurpleBod1433.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1434.geometry}
        material={nodes.UfoPurpleBod1434.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1435.geometry}
        material={nodes.UfoPurpleBod1435.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1436.geometry}
        material={nodes.UfoPurpleBod1436.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1437.geometry}
        material={nodes.UfoPurpleBod1437.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1438.geometry}
        material={nodes.UfoPurpleBod1438.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1439.geometry}
        material={nodes.UfoPurpleBod1439.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1440.geometry}
        material={nodes.UfoPurpleBod1440.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1441.geometry}
        material={nodes.UfoPurpleBod1441.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1458.geometry}
        material={nodes.UfoPurpleBod1458.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1459.geometry}
        material={nodes.UfoPurpleBod1459.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1462.geometry}
        material={nodes.UfoPurpleBod1462.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1463.geometry}
        material={nodes.UfoPurpleBod1463.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1466.geometry}
        material={nodes.UfoPurpleBod1466.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1467.geometry}
        material={nodes.UfoPurpleBod1467.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1476.geometry}
        material={nodes.UfoPurpleBod1476.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1477.geometry}
        material={nodes.UfoPurpleBod1477.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1478.geometry}
        material={nodes.UfoPurpleBod1478.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1479.geometry}
        material={nodes.UfoPurpleBod1479.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1481.geometry}
        material={nodes.UfoPurpleBod1481.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1482.geometry}
        material={nodes.UfoPurpleBod1482.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1488.geometry}
        material={nodes.UfoPurpleBod1488.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1489.geometry}
        material={nodes.UfoPurpleBod1489.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1490.geometry}
        material={nodes.UfoPurpleBod1490.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1491.geometry}
        material={nodes.UfoPurpleBod1491.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1498.geometry}
        material={nodes.UfoPurpleBod1498.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1505.geometry}
        material={nodes.UfoPurpleBod1505.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1518.geometry}
        material={nodes.UfoPurpleBod1518.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1519.geometry}
        material={nodes.UfoPurpleBod1519.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1520.geometry}
        material={nodes.UfoPurpleBod1520.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1521.geometry}
        material={nodes.UfoPurpleBod1521.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1522.geometry}
        material={nodes.UfoPurpleBod1522.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1529.geometry}
        material={nodes.UfoPurpleBod1529.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1530.geometry}
        material={nodes.UfoPurpleBod1530.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1535.geometry}
        material={nodes.UfoPurpleBod1535.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1536.geometry}
        material={nodes.UfoPurpleBod1536.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1537.geometry}
        material={nodes.UfoPurpleBod1537.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1538.geometry}
        material={nodes.UfoPurpleBod1538.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1539.geometry}
        material={nodes.UfoPurpleBod1539.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1540.geometry}
        material={nodes.UfoPurpleBod1540.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1548.geometry}
        material={nodes.UfoPurpleBod1548.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1549.geometry}
        material={nodes.UfoPurpleBod1549.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1550.geometry}
        material={nodes.UfoPurpleBod1550.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1551.geometry}
        material={nodes.UfoPurpleBod1551.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1557.geometry}
        material={nodes.UfoPurpleBod1557.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1558.geometry}
        material={nodes.UfoPurpleBod1558.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1561.geometry}
        material={nodes.UfoPurpleBod1561.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1562.geometry}
        material={nodes.UfoPurpleBod1562.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1563.geometry}
        material={nodes.UfoPurpleBod1563.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1568.geometry}
        material={nodes.UfoPurpleBod1568.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1569.geometry}
        material={nodes.UfoPurpleBod1569.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1570.geometry}
        material={nodes.UfoPurpleBod1570.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1571.geometry}
        material={nodes.UfoPurpleBod1571.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1572.geometry}
        material={nodes.UfoPurpleBod1572.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1573.geometry}
        material={nodes.UfoPurpleBod1573.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1574.geometry}
        material={nodes.UfoPurpleBod1574.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1575.geometry}
        material={nodes.UfoPurpleBod1575.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1576.geometry}
        material={nodes.UfoPurpleBod1576.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1579.geometry}
        material={nodes.UfoPurpleBod1579.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1586.geometry}
        material={nodes.UfoPurpleBod1586.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1587.geometry}
        material={nodes.UfoPurpleBod1587.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1591.geometry}
        material={nodes.UfoPurpleBod1591.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1592.geometry}
        material={nodes.UfoPurpleBod1592.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1593.geometry}
        material={nodes.UfoPurpleBod1593.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1594.geometry}
        material={nodes.UfoPurpleBod1594.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1595.geometry}
        material={nodes.UfoPurpleBod1595.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1596.geometry}
        material={nodes.UfoPurpleBod1596.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1597.geometry}
        material={nodes.UfoPurpleBod1597.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1599.geometry}
        material={nodes.UfoPurpleBod1599.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1600.geometry}
        material={nodes.UfoPurpleBod1600.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1608.geometry}
        material={nodes.UfoPurpleBod1608.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1609.geometry}
        material={nodes.UfoPurpleBod1609.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1610.geometry}
        material={nodes.UfoPurpleBod1610.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1611.geometry}
        material={nodes.UfoPurpleBod1611.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1614.geometry}
        material={nodes.UfoPurpleBod1614.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1615.geometry}
        material={nodes.UfoPurpleBod1615.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1618.geometry}
        material={nodes.UfoPurpleBod1618.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1619.geometry}
        material={nodes.UfoPurpleBod1619.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1628.geometry}
        material={nodes.UfoPurpleBod1628.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1629.geometry}
        material={nodes.UfoPurpleBod1629.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1631.geometry}
        material={nodes.UfoPurpleBod1631.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1632.geometry}
        material={nodes.UfoPurpleBod1632.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1635.geometry}
        material={nodes.UfoPurpleBod1635.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1636.geometry}
        material={nodes.UfoPurpleBod1636.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1644.geometry}
        material={nodes.UfoPurpleBod1644.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1645.geometry}
        material={nodes.UfoPurpleBod1645.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1673.geometry}
        material={nodes.UfoPurpleBod1673.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1674.geometry}
        material={nodes.UfoPurpleBod1674.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1689.geometry}
        material={nodes.UfoPurpleBod1689.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1690.geometry}
        material={nodes.UfoPurpleBod1690.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1691.geometry}
        material={nodes.UfoPurpleBod1691.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1692.geometry}
        material={nodes.UfoPurpleBod1692.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1723.geometry}
        material={nodes.UfoPurpleBod1723.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1724.geometry}
        material={nodes.UfoPurpleBod1724.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1731.geometry}
        material={nodes.UfoPurpleBod1731.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1732.geometry}
        material={nodes.UfoPurpleBod1732.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1733.geometry}
        material={nodes.UfoPurpleBod1733.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1734.geometry}
        material={nodes.UfoPurpleBod1734.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1735.geometry}
        material={nodes.UfoPurpleBod1735.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1736.geometry}
        material={nodes.UfoPurpleBod1736.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1737.geometry}
        material={nodes.UfoPurpleBod1737.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1738.geometry}
        material={nodes.UfoPurpleBod1738.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1743.geometry}
        material={nodes.UfoPurpleBod1743.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1744.geometry}
        material={nodes.UfoPurpleBod1744.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1745.geometry}
        material={nodes.UfoPurpleBod1745.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1746.geometry}
        material={nodes.UfoPurpleBod1746.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1752.geometry}
        material={nodes.UfoPurpleBod1752.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1753.geometry}
        material={nodes.UfoPurpleBod1753.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1779.geometry}
        material={nodes.UfoPurpleBod1779.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1780.geometry}
        material={nodes.UfoPurpleBod1780.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1781.geometry}
        material={nodes.UfoPurpleBod1781.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.UfoPurpleBod1782.geometry}
        material={nodes.UfoPurpleBod1782.material}
        position={[2.04, 0.04, 7.01]}
        rotation={[0, 0, -3.14]}
        scale={[7.63, 1, 7.63]}
      />
      <group position={[0.82, 0.6, 0.31]} rotation={[1.57, 0, -3.14]} scale={[14.68, 0.72, 14.68]}>
        <mesh geometry={nodes.path0003.geometry} material={materials['SVGMat.608']} />
        <mesh geometry={nodes.path0003_1.geometry} material={materials['SVGMat.118']} />
        <mesh geometry={nodes.path0003_2.geometry} material={materials['SVGMat.119']} />
        <mesh geometry={nodes.path0003_3.geometry} material={materials['SVGMat.156']} />
        <mesh geometry={nodes.path0003_4.geometry} material={materials['SVGMat.157']} />
        <mesh geometry={nodes.path0003_5.geometry} material={materials['SVGMat.366']} />
        <mesh geometry={nodes.path0003_6.geometry} material={materials['SVGMat.368']} />
        <mesh geometry={nodes.path0003_7.geometry} material={materials['SVGMat.369']} />
        <mesh geometry={nodes.path0003_8.geometry} material={materials['SVGMat.370']} />
        <mesh geometry={nodes.path0003_9.geometry} material={materials['SVGMat.472']} />
        <mesh geometry={nodes.path0003_10.geometry} material={materials['SVGMat.120']} />
        <mesh geometry={nodes.path0003_11.geometry} material={materials['SVGMat.624']} />
        <mesh geometry={nodes.path0003_12.geometry} material={materials['SVGMat.013']} />
      </group>
    </group>
  )
}

useGLTF.preload('https://racho-devs.s3.us-east-2.amazonaws.com/about/glbDivs/CarBit.glb')
