/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Design.glb for 3D models 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export default function Design(props) {
  const { nodes, materials } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/about/glbDivs/Design.glb')
  return (
    <group  position={[-0.5, -0.5, 1.5]}  rotation = {[Math.PI / 2, 0, 0]}  scale={1.85}  {...props} dispose={null}>
      <mesh geometry={nodes.Curve10398.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Curve316.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Curve315.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Curve306.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Curve302.geometry} material={materials.PaletteMaterial001} />
    </group>
  )
}

useGLTF.preload('https://racho-devs.s3.us-east-2.amazonaws.com/about/glbDivs/Design.glb')
