/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export default function Tease(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/about/glbDivs/RoomTeaseCompressed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group position={[0.15,-0.75,0]} scale={0.1} ref={group} {...props} dispose={null}>
      <group rotation={[-0.13, -0.18, -0.17]}>
        <group position={[0, 1.8, 0]} rotation={[-Math.PI, 0, 0]} scale={[1.02, 1.8, 1.02]}>
          <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
        </group>
        <mesh geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 0.32, 1]}>
          <mesh geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.54, 1]}>
          <mesh geometry={nodes.Object_13.geometry} material={nodes.Object_13.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.13, 1]}>
          <mesh geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 0.79, 1]}>
          <mesh geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 0.44, 1]}>
          <mesh geometry={nodes.Object_19.geometry} material={nodes.Object_19.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.2, 1]}>
          <mesh geometry={nodes.Object_21.geometry} material={nodes.Object_21.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 0.41, 1]}>
          <mesh geometry={nodes.Object_23.geometry} material={nodes.Object_23.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.35, 1]}>
          <mesh geometry={nodes.Object_25.geometry} material={nodes.Object_25.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 0.62, 1]}>
          <mesh geometry={nodes.Object_27.geometry} material={nodes.Object_27.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 0.95, 1]}>
          <mesh geometry={nodes.Object_29.geometry} material={nodes.Object_29.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 0.29, 1]}>
          <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 0.55, 1]}>
          <mesh geometry={nodes.Object_33.geometry} material={nodes.Object_33.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.54, 1]}>
          <mesh geometry={nodes.Object_35.geometry} material={nodes.Object_35.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.71, 1]}>
          <mesh geometry={nodes.Object_37.geometry} material={nodes.Object_37.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 0.86, 1]}>
          <mesh geometry={nodes.Object_39.geometry} material={nodes.Object_39.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.2, 1]}>
          <mesh geometry={nodes.Object_41.geometry} material={nodes.Object_41.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.13, 1]}>
          <mesh geometry={nodes.Object_43.geometry} material={nodes.Object_43.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 0.83, 1]}>
          <mesh geometry={nodes.Object_45.geometry} material={nodes.Object_45.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 0.37, 1]}>
          <mesh geometry={nodes.Object_47.geometry} material={nodes.Object_47.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 0.85, 1]}>
          <mesh geometry={nodes.Object_49.geometry} material={nodes.Object_49.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.04, 1]}>
          <mesh geometry={nodes.Object_51.geometry} material={nodes.Object_51.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.45, 1]}>
          <mesh geometry={nodes.Object_31.geometry} material={nodes.Object_31.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.36, 1]}>
          <mesh geometry={nodes.Object_55.geometry} material={nodes.Object_55.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.04, 1]}>
          <mesh geometry={nodes.Object_57.geometry} material={nodes.Object_57.material} />
        </group>
        <group position={[0, 0.01, 0]} rotation={[-Math.PI, 0, 0]} scale={[1, 0.92, 1]}>
          <mesh geometry={nodes.Object_59.geometry} material={nodes.Object_59.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.8, 1]}>
          <mesh geometry={nodes.Object_53.geometry} material={nodes.Object_53.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 0.72, 1]}>
          <mesh geometry={nodes.Object_61.geometry} material={nodes.Object_61.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.57, 1]}>
          <mesh geometry={nodes.Object_63.geometry} material={nodes.Object_63.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.03, 1]}>
          <mesh geometry={nodes.Object_65.geometry} material={nodes.Object_65.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 1.77, 1]}>
          <mesh geometry={nodes.Object_67.geometry} material={nodes.Object_67.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 0.59, 1]}>
          <mesh geometry={nodes.Object_69.geometry} material={nodes.Object_69.material} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={[1, 0.52, 1]}>
          <mesh geometry={nodes.Object_71.geometry} material={nodes.Object_71.material} />
        </group>
        <group name="linees_34" rotation={[-Math.PI, 0, 0]} scale={[0.99, 1.8, 0.99]}>
          <mesh geometry={nodes.Object_73.geometry} material={nodes.Object_73.material} />
          <mesh geometry={nodes.Object_74.geometry} material={materials['Material.003']} />
        </group>
      </group>
      <group position={[-4.09, 11.05, -0.16]} rotation={[-0.14, 0.42, 0.03]} scale={[0.56, 0.47, 0.56]}>
        <group name="Hat_0">
          <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} position={[1.65, -1.88, 0.28]} />
        </group>
      </group>
      <group position={[-6.06, 6.49, 3.51]} rotation={[-0.18, 0.09, 0.21]} scale={[0.03, 0.04, 0.04]}>
        <mesh geometry={nodes.Body005_1.geometry} material={materials['ARCADE.002']} />
        <mesh geometry={nodes.Body005_2.geometry} material={materials['PaletteMaterial001.001']} />
        <mesh geometry={nodes.Body005_3.geometry} material={materials['PaletteMaterial002.001']} />
        <mesh geometry={nodes.Body005_4.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Body005_5.geometry} material={nodes.Body005_5.material} />
        <mesh geometry={nodes.Body005_6.geometry} material={nodes.Body005_6.material} />
        <mesh geometry={nodes.Body005_7.geometry} material={nodes.Body005_7.material} />
      </group>
      <mesh geometry={nodes.Object_83.geometry} material={nodes.Object_83.material} rotation={[-0.13, -0.18, -0.17]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.blackFabric} rotation={[-0.13, -0.18, -0.17]} />
      <mesh geometry={nodes.Object_77.geometry} material={materials.frontColor} rotation={[-0.13, -0.18, -0.17]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.blackInternal} rotation={[-0.13, -0.18, -0.17]} />
    </group>
  )
}

useGLTF.preload('https://racho-devs.s3.us-east-2.amazonaws.com/about/glbDivs/RoomTeaseCompressed.glb')
