/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useEffect, useRef } from 'react'

export default function RoomChandelier({props, scaler}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/about/glbDivs/RoomChandelier.glb')
  const { actions } = useAnimations(animations, group)
  
  // Use effect to set the actions when the component mounts
  useEffect(() => {

  

    Object.keys(actions).forEach((key) => {
      actions[key].play();
    });
  
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null} scale={scaler ? 0.0025 : 1}>
      <group position={[-49.33, -51.92, 49.9]} rotation={[-Math.PI / 2, 0, 0]} scale={[20, 20, 20]} />
      <group scale={[22.27, 20.67, 22.06]}>
        <mesh geometry={nodes.circle_constant1_0.geometry} material={nodes.circle_constant1_0.material} />
        <mesh geometry={nodes.circle_HoloFillDark_0.geometry} material={materials.HoloFillDark} />
        <mesh geometry={nodes.circle1_constant2_0.geometry} material={nodes.circle1_constant2_0.material} />
        <mesh geometry={nodes.circle2_constant2_0.geometry} material={nodes.circle2_constant2_0.material} />
        <group name="geo1">
          <mesh geometry={nodes.geo1_constant1_0.geometry} material={nodes.geo1_constant1_0.material} />
        </group>
      </group>
      <group position={[8.36, -7.14, 0.31]} rotation={[1.57, 0, -3.14]} scale={[155.57, 7.62, 155.58]}>
        <mesh geometry={nodes.path0003.geometry} material={materials['SVGMat.608']} />
        <mesh geometry={nodes.path0003_1.geometry} material={materials['SVGMat.118']} />
        <mesh geometry={nodes.path0003_2.geometry} material={materials['SVGMat.119']} />
        <mesh geometry={nodes.path0003_3.geometry} material={materials['SVGMat.156']} />
        <mesh geometry={nodes.path0003_4.geometry} material={materials['SVGMat.157']} />
        <mesh geometry={nodes.path0003_5.geometry} material={materials['SVGMat.366']} />
        <mesh geometry={nodes.path0003_6.geometry} material={materials['SVGMat.368']} />
        <mesh geometry={nodes.path0003_7.geometry} material={materials['SVGMat.369']} />
        <mesh geometry={nodes.path0003_8.geometry} material={materials['SVGMat.370']} />
        <mesh geometry={nodes.path0003_9.geometry} material={materials['SVGMat.472']} />
        <mesh geometry={nodes.path0003_10.geometry} material={materials['SVGMat.120']} />
        <mesh geometry={nodes.path0003_11.geometry} material={materials['SVGMat.624']} />
        <mesh geometry={nodes.path0003_12.geometry} material={materials['SVGMat.013']} />
      </group>
    </group>
  )
}

useGLTF.preload('https://racho-devs.s3.us-east-2.amazonaws.com/about/glbDivs/RoomChandelier.glb')
