/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/RoomTease.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.48, 0.09, -0.21]} rotation={[-1.45, -0.18, -0.17]} scale={[0.01, 0.01, 0.01]} />
      <group position={[0.4, 0.14, -0.39]} rotation={[-1.45, 0.42, 0.03]} scale={[0.02, 0.01, 0.02]}>
        <group name="Hat_0001">
          <mesh
            geometry={nodes.Object_4001.geometry}
            material={nodes.Object_4001.material}
            position={[-11.3, 3.97, -9.12]}
            scale={[0.69, 1.1, 0.54]}
          />
        </group>
      </group>
      <group position={[0.42, 0.04, -0.1]} rotation={[-1.45, -0.18, -0.17]} scale={[0.02, 0.02, 0.02]}>
        <mesh geometry={nodes.Object_38001.geometry} material={materials['blackInternal.001']} />
        <mesh geometry={nodes.Object_38001_1.geometry} material={materials['equalizer.001']} />
        <mesh geometry={nodes.Object_38001_2.geometry} material={materials['PaletteMaterial001.002']} />
        <mesh geometry={nodes.Object_38001_3.geometry} material={nodes.Object_38001_3.material} />
        <mesh geometry={nodes.Object_38001_4.geometry} material={materials['blackFabric.001']} />
        <mesh geometry={nodes.Object_38001_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_38001_6.geometry} material={materials['PaletteMaterial003.002']} />
        <mesh geometry={nodes.Object_38001_7.geometry} material={materials['PaletteMaterial002.003']} />
      </group>
      <group position={[0.18, 0.08, -0.17]} rotation={[-1.55, 0.01, 0.4]} scale={[0, 0, 0]}>
        <mesh geometry={nodes.Icosphere442.geometry} material={materials['PaletteMaterial001.004']} />
        <mesh geometry={nodes.Icosphere442_1.geometry} material={materials['ARCADE.003']} />
        <mesh geometry={nodes.Icosphere442_2.geometry} material={materials['PaletteMaterial002.006']} />
        <mesh geometry={nodes.Icosphere442_3.geometry} material={materials['PaletteMaterial003.004']} />
        <mesh geometry={nodes.Icosphere442_4.geometry} material={materials['PaletteMaterial002.007']} />
        <mesh geometry={nodes.Icosphere442_5.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Icosphere442_6.geometry} material={materials.PaletteMaterial001} />
      </group>
    </group>
  )
}

useGLTF.preload('/RoomTease.glb')
