/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useEffect, useRef } from 'react'

export default function BoatMeBit(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/services/glb/BoatMeBit.glb')
  const { actions } = useAnimations(animations, group)
    
  // Use effect to set the actions when the component mounts
  useEffect(() => {
    Object.keys(actions).forEach((key) => {
      actions[key].play();
    });
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve001.geometry}
        material={materials.PaletteMaterial001}
        position={[0.13, -0.02, -0.07]}
        scale={[-0.96, -0.95, -0.95]}
      />
      <mesh
        geometry={nodes.Curve072.geometry}
        material={materials['SVGMat.029']}
        position={[0.39, 0, -0.09]}
        rotation={[0, -0.18, 0]}
      />
      <mesh
        geometry={nodes.Curve896.geometry}
        material={materials['Material.002']}
        position={[2.54, 26.8, 0.34]}
        rotation={[1.57, -0.18, 0]}
        scale={[147.65, 409.79, 192.19]}
      />
      <mesh
        geometry={nodes.Curve1370.geometry}
        material={materials['Material.006']}
        position={[2.54, 26.8, 0.34]}
        rotation={[1.57, -0.18, 0]}
        scale={[147.65, 409.79, 192.19]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials['Material.007']}
        position={[4.84, -11.98, 0.28]}
        rotation={[-1.57, -1.13, 0]}
        scale={[-2.26, -1.53, -1.02]}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials['Material.001']}
        position={[3.24, -15.48, 0.2]}
        rotation={[-1.57, -1.14, 0]}
        scale={[-1.32, -3.11, -0.96]}
      />
      <mesh
        name="Mesh_0"
        geometry={nodes.Mesh_0.geometry}
        material={materials['Material.005']}
        morphTargetDictionary={nodes.Mesh_0.morphTargetDictionary}
        morphTargetInfluences={nodes.Mesh_0.morphTargetInfluences}
        position={[0.3, 0.34, 0.35]}
        rotation={[-Math.PI / 2, 0, -1.61]}
        scale={[1.44, 1.03, 1.29]}
      />
    </group>
  )
}

useGLTF.preload('https://racho-devs.s3.us-east-2.amazonaws.com/services/glb/BoatMeBit.glb')
