/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Artsem Kalitsenya (https://sketchfab.com/DonKalishman)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/crystal-golem-heart-53d0e4d69acc413e99d27680cddd11ac
title: Crystal Golem Heart
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/crystal4.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['Hart_02_-_Default_0'].geometry}
        material={materials['02_-_Default']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/crystal4.glb')
