/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: LowlyPoly (https://sketchfab.com/lowlypoly)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stylized-tree-by-lowlypoly-96bfe5f5fe3e43e9b4db5ab78fd12710
title: Stylized Tree by Lowlypoly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/crystal5.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.plants_10_wood_text_plants_04_0.geometry} material={materials.text_plants_04} />
      <mesh geometry={nodes.plants_10_leaf_text_grass_0.geometry} material={materials.text_grass} />
    </group>
  )
}

useGLTF.preload('/crystal5.glb')
