/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: tamminen (https://sketchfab.com/tamminen)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/gemer-8e914bc2ba14443784bad702d80b377e
title: Gemer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/crystal3.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} />
    </group>
  )
}

useGLTF.preload('/crystal3.glb')
