/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/crystal-dc521f0925fb4f67b969d53e001d5bfe
title: Crystal
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/crystal2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['CrystalOne_LP_Material_#1_0'].geometry}
        material={materials.Material_1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/crystal2.glb')
