/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: orca_studio (https://sketchfab.com/orca_studio)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ugly-face-monster-8c2e666b04f04bcab1e86a2dd3d77ecc
title: ugly face  monster
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export default function Alien({props, color}) {
  const group = useRef()
  const { nodes, materials } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/fun/glb/SkyBlitz/alien.glb')
  return (
    <group scale={0.005} position={[0, -0.75, 0]} rotation={[0,-Math.PI / 2,0]} ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} color={color} rotation={[0, Math.PI / 2, 0]} >

      <meshBasicMaterial color={color} />
      </mesh>

    </group>
  )
}

useGLTF.preload('https://racho-devs.s3.us-east-2.amazonaws.com/fun/glb/SkyBlitz/alien.glb')
