/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export default function Model(props) {
  const group = useRef()
  const Paddle = 'https://racho-devs.s3.us-east-2.amazonaws.com/myProjects/glbModels/Crystals/PaddleHand.glb'
  const { nodes, materials } = useGLTF(Paddle)
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Bone} />
      <primitive object={nodes.Bone003} />
      <primitive object={nodes.Bone006} />
      <primitive object={nodes.Bone010} />
      <skinnedMesh geometry={nodes.arm.geometry} material={materials.glove} skeleton={nodes.arm.skeleton} />
      <mesh
        geometry={nodes.SM_PingPongPaddle_M_PingPongPaddle_0.geometry}
        material={materials['M_PingPongPaddle.001']}
      />
      <mesh
        geometry={nodes.SM_PingPongPaddle_M_PingPongPaddle_0001.geometry}
        material={materials['M_PingPongPaddle.002']}
      />
    </group>
  )
}

useGLTF.preload(Paddle)
