/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'
import Paddle from '../glbModels/Paddle.glb'
export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(Paddle)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.SM_PingPongPaddle_M_PingPongPaddle_0.geometry}
        material={materials.M_PingPongPaddle}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload(Paddle)
