/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'
import RachoArcade from '/rachoArcade.glb'
export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(RachoArcade)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[6.84, 0, 0.19]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-6.42, -16.04, 50.04]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.STEEL003.geometry} material={materials['STEEL.003']} />
          <mesh geometry={nodes.STEEL003_1.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.STEEL003_2.geometry} material={materials['STEEL.001']} />
        </group>
      </group>
      <group position={[-117.12, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[116.91, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.08, 36.27, 13.79]}>
            <mesh geometry={nodes.STEEL2002.geometry} material={materials['STEEL2.001']} />
          </group>
        </group>
      </group>
      <mesh
        geometry={nodes.ArcadeTopBanner.geometry}
        material={materials['ARCADE.002']}
        position={[0.62, 146.59, 8.96]}
      />
      <group position={[0.64, 110.48, -13.61]} rotation={[-0.18, 0, 0]}>
        <mesh geometry={nodes.Body_1.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Body_3.geometry} material={materials.PaletteMaterial003} />
      </group>
      <mesh
        geometry={nodes.Front_Board_Bottom.geometry}
        material={nodes.Front_Board_Bottom.material}
        position={[-8.84, 7.33, 11.13]}
        rotation={[1.4, 0, 0]}
        scale={[34.94, 1, 48.88]}
      />
      <mesh
        geometry={nodes.Front_Board.geometry}
        material={nodes.Front_Board.material}
        position={[-8.84, 7.33, 11.13]}
        rotation={[1.4, 0, 0]}
        scale={[34.94, 1, 48.88]}
      />
      <mesh
        geometry={nodes.Yellow_Button.geometry}
        material={materials['Material.001']}
        position={[-12.47, 78.5, 17.76]}
        rotation={[0.39, 0.33, 0.01]}
        scale={[1.14, 1.04, 1.13]}
      />
      <group position={[-0.28, 80.78, 13.53]} rotation={[0.4, 0, 0]} scale={[4.59, 3.72, 4.72]}>
        <mesh geometry={nodes.Sphere.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Sphere_1.geometry} material={materials['Material.007']} />
      </group>
      <mesh
        geometry={nodes.Purple_Button.geometry}
        material={materials['Material.005']}
        position={[-23.18, 77.78, 19.7]}
        rotation={[0.24, 0.01, 0.04]}
        scale={[1.96, 1.73, 1.96]}
      />
      <mesh
        geometry={nodes.Sweep_NURBS_NEON_0003.geometry}
        material={materials['PaletteMaterial002.001']}
        position={[32.79, 0, -0.87]}
      />
      <mesh
        geometry={nodes.Blue_Button.geometry}
        material={materials['Material.004']}
        position={[-21.32, 80.54, 11.45]}
        rotation={[0.39, 0.33, 0.01]}
        scale={[1.14, 1.04, 1.13]}
      />
      <mesh
        geometry={nodes.Green_Button.geometry}
        material={materials['Material.003']}
        position={[-17.25, 79.32, 14.79]}
        rotation={[0.39, 0.33, 0.01]}
        scale={[1.14, 1.04, 1.13]}
      />
      <group position={[17.91, 87.59, 12.86]} scale={[1.5, 1.32, 1.5]}>
        <mesh geometry={nodes.Icosphere442.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Icosphere442_1.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Icosphere442_2.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Icosphere442_3.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Icosphere442_4.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Icosphere442_5.geometry} material={materials['STEEL.002']} />
        <mesh geometry={nodes.Icosphere442_6.geometry} material={nodes.Icosphere442_6.material} />
      </group>
      <mesh
        geometry={nodes.Body_2.geometry}
        material={nodes.Body_2.material}
        position={[17.91, 87.59, 12.86]}
        scale={[1.5, 1.32, 1.5]}
      />
      <mesh
        geometry={nodes.Body_2001.geometry}
        material={nodes.Body_2001.material}
        position={[17.91, 87.59, 12.86]}
        scale={[1.5, 1.32, 1.5]}
      />
      <mesh
        geometry={nodes.MAIN_SCREEN002.geometry}
        material={materials['PaletteMaterial001.004']}
        position={[-8.84, 6.99, 12.25]}
        rotation={[1.41, 0, 0]}
        scale={[34.94, 1, 48.88]}
      />
    </group>
  )
}

useGLTF.preload(RachoArcade)
