/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Payam Tavakoli (https://sketchfab.com/payamtavakoli)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/sci-fi-monitor-37a0fbbf74cd41bdb91c37156954d7c1
title: Sci fi Monitor
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Model(props) {
  const { nodes, materials } = useGLTF('../glbModels/sci_fi_monitor.glb')
  return (
    <group {...props} dispose={null} position={[-12, 35, -10]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['Material.010']} />
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.012']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.None} />
            <mesh geometry={nodes.Object_8.geometry} material={materials['Material.011']} />
            <mesh geometry={nodes.Object_9.geometry} material={materials['Material.018']} />
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.019']} />
            <mesh geometry={nodes.Object_11.geometry} material={materials['Material.014']} />
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.013']} />
            <mesh geometry={nodes.Object_13.geometry} material={materials['Material.015']} />
            <mesh geometry={nodes.Object_14.geometry} material={materials['Material.016']} />
            <mesh geometry={nodes.Object_15.geometry} material={materials['Material.017']} />
            <mesh geometry={nodes.Object_16.geometry} material={materials['Material.002']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../glbModels/sci_fi_monitor.glb')
