/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'
function ScreenInteractive(props) {
  return (
    <Screen {...props}>
      <PerspectiveCamera makeDefault manual aspect={1 / 1} position={[0, 0, 10]} />
      <color attach="background" args={['orange']} />
      <ambientLight intensity={0.2} />
      <pointLight position={[10, 10, 10]} intensity={0.75} />
      <pointLight position={[-10, -10, -10]} />
      <SpinningBox position={[-3.15, 0.75, 0]} scale={0.5} />
    </Screen>
  )
}
export default function Screens(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Screens.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.71, -7.07, 0.47]} rotation={[-Math.PI / 2, 0, -2.24]} scale={[0.79, 1, 0.75]}>
        <ScreenInteractive
          frame="Object_2020"
          geometry={nodes.Object_2020.geometry}
         // material={materials['object1_auv.007']}
          position={[11.58, 6.4, 0.8]}
          rotation={[0, 0, -0.8]}
          scale={[0.41, 0.47, 0.44]}
        />
      </group>
      <group position={[-0.13, -7.07, -2.19]} rotation={[-Math.PI / 2, 0, -1.48]} scale={[0.79, 1, 0.75]}>
        <ScreenInteractive
          frame="Object_2021"
          geometry={nodes.Object_2021.geometry}
         // material={materials['object1_auv.008']}
          position={[6.9, 10.13, 1.03]}
          rotation={[0, 0, -0.43]}
          scale={[0.43, 0.31, 0.43]}
        />
      </group>
      <group position={[0.29, -7.07, -1.77]} rotation={[-Math.PI / 2, 0, 2.35]} scale={[0.79, 1, 0.75]}>
        <ScreenInteractive
          frame="Object_2022"
          geometry={nodes.Object_2022.geometry}
        //  material={materials['object1_auv.009']}
          position={[5.16, 10.4, 0.7]}
          rotation={[0, 0, -0.34]}
          scale={[0.45, 0.39, 0.41]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./glb/Screens.glb')
